package com.example.ez.mapper;

import com.example.ez.po.YesapiTrackMovie;
import com.example.ez.po.YesapiTrackMovieExample;
import com.example.ez.po.YesapiTrackMovieWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YesapiTrackMovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    int countByExample(YesapiTrackMovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    int deleteByExample(YesapiTrackMovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    int insert(YesapiTrackMovieWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    int insertSelective(YesapiTrackMovieWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    List<YesapiTrackMovieWithBLOBs> selectByExampleWithBLOBs(YesapiTrackMovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    List<YesapiTrackMovie> selectByExample(YesapiTrackMovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    YesapiTrackMovieWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    int updateByExampleSelective(@Param("record") YesapiTrackMovieWithBLOBs record, @Param("example") YesapiTrackMovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") YesapiTrackMovieWithBLOBs record, @Param("example") YesapiTrackMovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    int updateByExample(@Param("record") YesapiTrackMovie record, @Param("example") YesapiTrackMovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    int updateByPrimaryKeySelective(YesapiTrackMovieWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(YesapiTrackMovieWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    int updateByPrimaryKey(YesapiTrackMovie record);
}