package com.example.ez.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class YesapiTrackMovieExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public YesapiTrackMovieExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameIsNull() {
            addCriterion("track_movie_name is null");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameIsNotNull() {
            addCriterion("track_movie_name is not null");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameEqualTo(String value) {
            addCriterion("track_movie_name =", value, "trackMovieName");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameNotEqualTo(String value) {
            addCriterion("track_movie_name <>", value, "trackMovieName");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameGreaterThan(String value) {
            addCriterion("track_movie_name >", value, "trackMovieName");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameGreaterThanOrEqualTo(String value) {
            addCriterion("track_movie_name >=", value, "trackMovieName");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameLessThan(String value) {
            addCriterion("track_movie_name <", value, "trackMovieName");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameLessThanOrEqualTo(String value) {
            addCriterion("track_movie_name <=", value, "trackMovieName");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameLike(String value) {
            addCriterion("track_movie_name like", value, "trackMovieName");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameNotLike(String value) {
            addCriterion("track_movie_name not like", value, "trackMovieName");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameIn(List<String> values) {
            addCriterion("track_movie_name in", values, "trackMovieName");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameNotIn(List<String> values) {
            addCriterion("track_movie_name not in", values, "trackMovieName");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameBetween(String value1, String value2) {
            addCriterion("track_movie_name between", value1, value2, "trackMovieName");
            return (Criteria) this;
        }

        public Criteria andTrackMovieNameNotBetween(String value1, String value2) {
            addCriterion("track_movie_name not between", value1, value2, "trackMovieName");
            return (Criteria) this;
        }

        public Criteria andForeignNameIsNull() {
            addCriterion("foreign_name is null");
            return (Criteria) this;
        }

        public Criteria andForeignNameIsNotNull() {
            addCriterion("foreign_name is not null");
            return (Criteria) this;
        }

        public Criteria andForeignNameEqualTo(String value) {
            addCriterion("foreign_name =", value, "foreignName");
            return (Criteria) this;
        }

        public Criteria andForeignNameNotEqualTo(String value) {
            addCriterion("foreign_name <>", value, "foreignName");
            return (Criteria) this;
        }

        public Criteria andForeignNameGreaterThan(String value) {
            addCriterion("foreign_name >", value, "foreignName");
            return (Criteria) this;
        }

        public Criteria andForeignNameGreaterThanOrEqualTo(String value) {
            addCriterion("foreign_name >=", value, "foreignName");
            return (Criteria) this;
        }

        public Criteria andForeignNameLessThan(String value) {
            addCriterion("foreign_name <", value, "foreignName");
            return (Criteria) this;
        }

        public Criteria andForeignNameLessThanOrEqualTo(String value) {
            addCriterion("foreign_name <=", value, "foreignName");
            return (Criteria) this;
        }

        public Criteria andForeignNameLike(String value) {
            addCriterion("foreign_name like", value, "foreignName");
            return (Criteria) this;
        }

        public Criteria andForeignNameNotLike(String value) {
            addCriterion("foreign_name not like", value, "foreignName");
            return (Criteria) this;
        }

        public Criteria andForeignNameIn(List<String> values) {
            addCriterion("foreign_name in", values, "foreignName");
            return (Criteria) this;
        }

        public Criteria andForeignNameNotIn(List<String> values) {
            addCriterion("foreign_name not in", values, "foreignName");
            return (Criteria) this;
        }

        public Criteria andForeignNameBetween(String value1, String value2) {
            addCriterion("foreign_name between", value1, value2, "foreignName");
            return (Criteria) this;
        }

        public Criteria andForeignNameNotBetween(String value1, String value2) {
            addCriterion("foreign_name not between", value1, value2, "foreignName");
            return (Criteria) this;
        }

        public Criteria andCoverIsNull() {
            addCriterion("cover is null");
            return (Criteria) this;
        }

        public Criteria andCoverIsNotNull() {
            addCriterion("cover is not null");
            return (Criteria) this;
        }

        public Criteria andCoverEqualTo(String value) {
            addCriterion("cover =", value, "cover");
            return (Criteria) this;
        }

        public Criteria andCoverNotEqualTo(String value) {
            addCriterion("cover <>", value, "cover");
            return (Criteria) this;
        }

        public Criteria andCoverGreaterThan(String value) {
            addCriterion("cover >", value, "cover");
            return (Criteria) this;
        }

        public Criteria andCoverGreaterThanOrEqualTo(String value) {
            addCriterion("cover >=", value, "cover");
            return (Criteria) this;
        }

        public Criteria andCoverLessThan(String value) {
            addCriterion("cover <", value, "cover");
            return (Criteria) this;
        }

        public Criteria andCoverLessThanOrEqualTo(String value) {
            addCriterion("cover <=", value, "cover");
            return (Criteria) this;
        }

        public Criteria andCoverLike(String value) {
            addCriterion("cover like", value, "cover");
            return (Criteria) this;
        }

        public Criteria andCoverNotLike(String value) {
            addCriterion("cover not like", value, "cover");
            return (Criteria) this;
        }

        public Criteria andCoverIn(List<String> values) {
            addCriterion("cover in", values, "cover");
            return (Criteria) this;
        }

        public Criteria andCoverNotIn(List<String> values) {
            addCriterion("cover not in", values, "cover");
            return (Criteria) this;
        }

        public Criteria andCoverBetween(String value1, String value2) {
            addCriterion("cover between", value1, value2, "cover");
            return (Criteria) this;
        }

        public Criteria andCoverNotBetween(String value1, String value2) {
            addCriterion("cover not between", value1, value2, "cover");
            return (Criteria) this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("duration is null");
            return (Criteria) this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("duration is not null");
            return (Criteria) this;
        }

        public Criteria andDurationEqualTo(Integer value) {
            addCriterion("duration =", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotEqualTo(Integer value) {
            addCriterion("duration <>", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThan(Integer value) {
            addCriterion("duration >", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("duration >=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThan(Integer value) {
            addCriterion("duration <", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThanOrEqualTo(Integer value) {
            addCriterion("duration <=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationIn(List<Integer> values) {
            addCriterion("duration in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotIn(List<Integer> values) {
            addCriterion("duration not in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationBetween(Integer value1, Integer value2) {
            addCriterion("duration between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("duration not between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andTrackMovieYearIsNull() {
            addCriterion("track_movie_year is null");
            return (Criteria) this;
        }

        public Criteria andTrackMovieYearIsNotNull() {
            addCriterion("track_movie_year is not null");
            return (Criteria) this;
        }

        public Criteria andTrackMovieYearEqualTo(Integer value) {
            addCriterion("track_movie_year =", value, "trackMovieYear");
            return (Criteria) this;
        }

        public Criteria andTrackMovieYearNotEqualTo(Integer value) {
            addCriterion("track_movie_year <>", value, "trackMovieYear");
            return (Criteria) this;
        }

        public Criteria andTrackMovieYearGreaterThan(Integer value) {
            addCriterion("track_movie_year >", value, "trackMovieYear");
            return (Criteria) this;
        }

        public Criteria andTrackMovieYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("track_movie_year >=", value, "trackMovieYear");
            return (Criteria) this;
        }

        public Criteria andTrackMovieYearLessThan(Integer value) {
            addCriterion("track_movie_year <", value, "trackMovieYear");
            return (Criteria) this;
        }

        public Criteria andTrackMovieYearLessThanOrEqualTo(Integer value) {
            addCriterion("track_movie_year <=", value, "trackMovieYear");
            return (Criteria) this;
        }

        public Criteria andTrackMovieYearIn(List<Integer> values) {
            addCriterion("track_movie_year in", values, "trackMovieYear");
            return (Criteria) this;
        }

        public Criteria andTrackMovieYearNotIn(List<Integer> values) {
            addCriterion("track_movie_year not in", values, "trackMovieYear");
            return (Criteria) this;
        }

        public Criteria andTrackMovieYearBetween(Integer value1, Integer value2) {
            addCriterion("track_movie_year between", value1, value2, "trackMovieYear");
            return (Criteria) this;
        }

        public Criteria andTrackMovieYearNotBetween(Integer value1, Integer value2) {
            addCriterion("track_movie_year not between", value1, value2, "trackMovieYear");
            return (Criteria) this;
        }

        public Criteria andTrackMovieReleaseIsNull() {
            addCriterion("track_movie_release is null");
            return (Criteria) this;
        }

        public Criteria andTrackMovieReleaseIsNotNull() {
            addCriterion("track_movie_release is not null");
            return (Criteria) this;
        }

        public Criteria andTrackMovieReleaseEqualTo(Date value) {
            addCriterionForJDBCDate("track_movie_release =", value, "trackMovieRelease");
            return (Criteria) this;
        }

        public Criteria andTrackMovieReleaseNotEqualTo(Date value) {
            addCriterionForJDBCDate("track_movie_release <>", value, "trackMovieRelease");
            return (Criteria) this;
        }

        public Criteria andTrackMovieReleaseGreaterThan(Date value) {
            addCriterionForJDBCDate("track_movie_release >", value, "trackMovieRelease");
            return (Criteria) this;
        }

        public Criteria andTrackMovieReleaseGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("track_movie_release >=", value, "trackMovieRelease");
            return (Criteria) this;
        }

        public Criteria andTrackMovieReleaseLessThan(Date value) {
            addCriterionForJDBCDate("track_movie_release <", value, "trackMovieRelease");
            return (Criteria) this;
        }

        public Criteria andTrackMovieReleaseLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("track_movie_release <=", value, "trackMovieRelease");
            return (Criteria) this;
        }

        public Criteria andTrackMovieReleaseIn(List<Date> values) {
            addCriterionForJDBCDate("track_movie_release in", values, "trackMovieRelease");
            return (Criteria) this;
        }

        public Criteria andTrackMovieReleaseNotIn(List<Date> values) {
            addCriterionForJDBCDate("track_movie_release not in", values, "trackMovieRelease");
            return (Criteria) this;
        }

        public Criteria andTrackMovieReleaseBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("track_movie_release between", value1, value2, "trackMovieRelease");
            return (Criteria) this;
        }

        public Criteria andTrackMovieReleaseNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("track_movie_release not between", value1, value2, "trackMovieRelease");
            return (Criteria) this;
        }

        public Criteria andMusicianIdIsNull() {
            addCriterion("musician_id is null");
            return (Criteria) this;
        }

        public Criteria andMusicianIdIsNotNull() {
            addCriterion("musician_id is not null");
            return (Criteria) this;
        }

        public Criteria andMusicianIdEqualTo(String value) {
            addCriterion("musician_id =", value, "musicianId");
            return (Criteria) this;
        }

        public Criteria andMusicianIdNotEqualTo(String value) {
            addCriterion("musician_id <>", value, "musicianId");
            return (Criteria) this;
        }

        public Criteria andMusicianIdGreaterThan(String value) {
            addCriterion("musician_id >", value, "musicianId");
            return (Criteria) this;
        }

        public Criteria andMusicianIdGreaterThanOrEqualTo(String value) {
            addCriterion("musician_id >=", value, "musicianId");
            return (Criteria) this;
        }

        public Criteria andMusicianIdLessThan(String value) {
            addCriterion("musician_id <", value, "musicianId");
            return (Criteria) this;
        }

        public Criteria andMusicianIdLessThanOrEqualTo(String value) {
            addCriterion("musician_id <=", value, "musicianId");
            return (Criteria) this;
        }

        public Criteria andMusicianIdLike(String value) {
            addCriterion("musician_id like", value, "musicianId");
            return (Criteria) this;
        }

        public Criteria andMusicianIdNotLike(String value) {
            addCriterion("musician_id not like", value, "musicianId");
            return (Criteria) this;
        }

        public Criteria andMusicianIdIn(List<String> values) {
            addCriterion("musician_id in", values, "musicianId");
            return (Criteria) this;
        }

        public Criteria andMusicianIdNotIn(List<String> values) {
            addCriterion("musician_id not in", values, "musicianId");
            return (Criteria) this;
        }

        public Criteria andMusicianIdBetween(String value1, String value2) {
            addCriterion("musician_id between", value1, value2, "musicianId");
            return (Criteria) this;
        }

        public Criteria andMusicianIdNotBetween(String value1, String value2) {
            addCriterion("musician_id not between", value1, value2, "musicianId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdIsNull() {
            addCriterion("director_id is null");
            return (Criteria) this;
        }

        public Criteria andDirectorIdIsNotNull() {
            addCriterion("director_id is not null");
            return (Criteria) this;
        }

        public Criteria andDirectorIdEqualTo(String value) {
            addCriterion("director_id =", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdNotEqualTo(String value) {
            addCriterion("director_id <>", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdGreaterThan(String value) {
            addCriterion("director_id >", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdGreaterThanOrEqualTo(String value) {
            addCriterion("director_id >=", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdLessThan(String value) {
            addCriterion("director_id <", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdLessThanOrEqualTo(String value) {
            addCriterion("director_id <=", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdLike(String value) {
            addCriterion("director_id like", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdNotLike(String value) {
            addCriterion("director_id not like", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdIn(List<String> values) {
            addCriterion("director_id in", values, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdNotIn(List<String> values) {
            addCriterion("director_id not in", values, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdBetween(String value1, String value2) {
            addCriterion("director_id between", value1, value2, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdNotBetween(String value1, String value2) {
            addCriterion("director_id not between", value1, value2, "directorId");
            return (Criteria) this;
        }

        public Criteria andActorIdIsNull() {
            addCriterion("actor_id is null");
            return (Criteria) this;
        }

        public Criteria andActorIdIsNotNull() {
            addCriterion("actor_id is not null");
            return (Criteria) this;
        }

        public Criteria andActorIdEqualTo(String value) {
            addCriterion("actor_id =", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdNotEqualTo(String value) {
            addCriterion("actor_id <>", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdGreaterThan(String value) {
            addCriterion("actor_id >", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdGreaterThanOrEqualTo(String value) {
            addCriterion("actor_id >=", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdLessThan(String value) {
            addCriterion("actor_id <", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdLessThanOrEqualTo(String value) {
            addCriterion("actor_id <=", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdLike(String value) {
            addCriterion("actor_id like", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdNotLike(String value) {
            addCriterion("actor_id not like", value, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdIn(List<String> values) {
            addCriterion("actor_id in", values, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdNotIn(List<String> values) {
            addCriterion("actor_id not in", values, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdBetween(String value1, String value2) {
            addCriterion("actor_id between", value1, value2, "actorId");
            return (Criteria) this;
        }

        public Criteria andActorIdNotBetween(String value1, String value2) {
            addCriterion("actor_id not between", value1, value2, "actorId");
            return (Criteria) this;
        }

        public Criteria andDoubanIdIsNull() {
            addCriterion("douban_id is null");
            return (Criteria) this;
        }

        public Criteria andDoubanIdIsNotNull() {
            addCriterion("douban_id is not null");
            return (Criteria) this;
        }

        public Criteria andDoubanIdEqualTo(Integer value) {
            addCriterion("douban_id =", value, "doubanId");
            return (Criteria) this;
        }

        public Criteria andDoubanIdNotEqualTo(Integer value) {
            addCriterion("douban_id <>", value, "doubanId");
            return (Criteria) this;
        }

        public Criteria andDoubanIdGreaterThan(Integer value) {
            addCriterion("douban_id >", value, "doubanId");
            return (Criteria) this;
        }

        public Criteria andDoubanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("douban_id >=", value, "doubanId");
            return (Criteria) this;
        }

        public Criteria andDoubanIdLessThan(Integer value) {
            addCriterion("douban_id <", value, "doubanId");
            return (Criteria) this;
        }

        public Criteria andDoubanIdLessThanOrEqualTo(Integer value) {
            addCriterion("douban_id <=", value, "doubanId");
            return (Criteria) this;
        }

        public Criteria andDoubanIdIn(List<Integer> values) {
            addCriterion("douban_id in", values, "doubanId");
            return (Criteria) this;
        }

        public Criteria andDoubanIdNotIn(List<Integer> values) {
            addCriterion("douban_id not in", values, "doubanId");
            return (Criteria) this;
        }

        public Criteria andDoubanIdBetween(Integer value1, Integer value2) {
            addCriterion("douban_id between", value1, value2, "doubanId");
            return (Criteria) this;
        }

        public Criteria andDoubanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("douban_id not between", value1, value2, "doubanId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andMovieStatusIsNull() {
            addCriterion("movie_status is null");
            return (Criteria) this;
        }

        public Criteria andMovieStatusIsNotNull() {
            addCriterion("movie_status is not null");
            return (Criteria) this;
        }

        public Criteria andMovieStatusEqualTo(Integer value) {
            addCriterion("movie_status =", value, "movieStatus");
            return (Criteria) this;
        }

        public Criteria andMovieStatusNotEqualTo(Integer value) {
            addCriterion("movie_status <>", value, "movieStatus");
            return (Criteria) this;
        }

        public Criteria andMovieStatusGreaterThan(Integer value) {
            addCriterion("movie_status >", value, "movieStatus");
            return (Criteria) this;
        }

        public Criteria andMovieStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("movie_status >=", value, "movieStatus");
            return (Criteria) this;
        }

        public Criteria andMovieStatusLessThan(Integer value) {
            addCriterion("movie_status <", value, "movieStatus");
            return (Criteria) this;
        }

        public Criteria andMovieStatusLessThanOrEqualTo(Integer value) {
            addCriterion("movie_status <=", value, "movieStatus");
            return (Criteria) this;
        }

        public Criteria andMovieStatusIn(List<Integer> values) {
            addCriterion("movie_status in", values, "movieStatus");
            return (Criteria) this;
        }

        public Criteria andMovieStatusNotIn(List<Integer> values) {
            addCriterion("movie_status not in", values, "movieStatus");
            return (Criteria) this;
        }

        public Criteria andMovieStatusBetween(Integer value1, Integer value2) {
            addCriterion("movie_status between", value1, value2, "movieStatus");
            return (Criteria) this;
        }

        public Criteria andMovieStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("movie_status not between", value1, value2, "movieStatus");
            return (Criteria) this;
        }

        public Criteria andIsRecommendIsNull() {
            addCriterion("is_recommend is null");
            return (Criteria) this;
        }

        public Criteria andIsRecommendIsNotNull() {
            addCriterion("is_recommend is not null");
            return (Criteria) this;
        }

        public Criteria andIsRecommendEqualTo(Integer value) {
            addCriterion("is_recommend =", value, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendNotEqualTo(Integer value) {
            addCriterion("is_recommend <>", value, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendGreaterThan(Integer value) {
            addCriterion("is_recommend >", value, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_recommend >=", value, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendLessThan(Integer value) {
            addCriterion("is_recommend <", value, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendLessThanOrEqualTo(Integer value) {
            addCriterion("is_recommend <=", value, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendIn(List<Integer> values) {
            addCriterion("is_recommend in", values, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendNotIn(List<Integer> values) {
            addCriterion("is_recommend not in", values, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendBetween(Integer value1, Integer value2) {
            addCriterion("is_recommend between", value1, value2, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendNotBetween(Integer value1, Integer value2) {
            addCriterion("is_recommend not between", value1, value2, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("valid is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("valid is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Boolean value) {
            addCriterion("valid =", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(Boolean value) {
            addCriterion("valid <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Boolean value) {
            addCriterion("valid >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("valid >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Boolean value) {
            addCriterion("valid <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Boolean value) {
            addCriterion("valid <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Boolean> values) {
            addCriterion("valid in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Boolean> values) {
            addCriterion("valid not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Boolean value1, Boolean value2) {
            addCriterion("valid between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("valid not between", value1, value2, "valid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 21 13:24:50 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yesapi_track_movie
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}