package com.example.ez.po;

import java.util.Date;

public class YesapiTrackMovie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.track_movie_name
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private String trackMovieName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.foreign_name
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private String foreignName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.cover
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.duration
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.track_movie_year
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private Integer trackMovieYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.track_movie_release
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private Date trackMovieRelease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.musician_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private String musicianId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.director_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private String directorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.actor_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private String actorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.douban_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private Integer doubanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.user_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.movie_status
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private Integer movieStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.is_recommend
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private Integer isRecommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.count
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.create_time
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.valid
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.id
     *
     * @return the value of yesapi_track_movie.id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.id
     *
     * @param id the value for yesapi_track_movie.id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.track_movie_name
     *
     * @return the value of yesapi_track_movie.track_movie_name
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public String getTrackMovieName() {
        return trackMovieName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.track_movie_name
     *
     * @param trackMovieName the value for yesapi_track_movie.track_movie_name
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setTrackMovieName(String trackMovieName) {
        this.trackMovieName = trackMovieName == null ? null : trackMovieName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.foreign_name
     *
     * @return the value of yesapi_track_movie.foreign_name
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public String getForeignName() {
        return foreignName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.foreign_name
     *
     * @param foreignName the value for yesapi_track_movie.foreign_name
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setForeignName(String foreignName) {
        this.foreignName = foreignName == null ? null : foreignName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.cover
     *
     * @return the value of yesapi_track_movie.cover
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.cover
     *
     * @param cover the value for yesapi_track_movie.cover
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.duration
     *
     * @return the value of yesapi_track_movie.duration
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.duration
     *
     * @param duration the value for yesapi_track_movie.duration
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.track_movie_year
     *
     * @return the value of yesapi_track_movie.track_movie_year
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Integer getTrackMovieYear() {
        return trackMovieYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.track_movie_year
     *
     * @param trackMovieYear the value for yesapi_track_movie.track_movie_year
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setTrackMovieYear(Integer trackMovieYear) {
        this.trackMovieYear = trackMovieYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.track_movie_release
     *
     * @return the value of yesapi_track_movie.track_movie_release
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Date getTrackMovieRelease() {
        return trackMovieRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.track_movie_release
     *
     * @param trackMovieRelease the value for yesapi_track_movie.track_movie_release
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setTrackMovieRelease(Date trackMovieRelease) {
        this.trackMovieRelease = trackMovieRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.musician_id
     *
     * @return the value of yesapi_track_movie.musician_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public String getMusicianId() {
        return musicianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.musician_id
     *
     * @param musicianId the value for yesapi_track_movie.musician_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setMusicianId(String musicianId) {
        this.musicianId = musicianId == null ? null : musicianId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.director_id
     *
     * @return the value of yesapi_track_movie.director_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public String getDirectorId() {
        return directorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.director_id
     *
     * @param directorId the value for yesapi_track_movie.director_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setDirectorId(String directorId) {
        this.directorId = directorId == null ? null : directorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.actor_id
     *
     * @return the value of yesapi_track_movie.actor_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public String getActorId() {
        return actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.actor_id
     *
     * @param actorId the value for yesapi_track_movie.actor_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setActorId(String actorId) {
        this.actorId = actorId == null ? null : actorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.douban_id
     *
     * @return the value of yesapi_track_movie.douban_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Integer getDoubanId() {
        return doubanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.douban_id
     *
     * @param doubanId the value for yesapi_track_movie.douban_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setDoubanId(Integer doubanId) {
        this.doubanId = doubanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.user_id
     *
     * @return the value of yesapi_track_movie.user_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.user_id
     *
     * @param userId the value for yesapi_track_movie.user_id
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.movie_status
     *
     * @return the value of yesapi_track_movie.movie_status
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Integer getMovieStatus() {
        return movieStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.movie_status
     *
     * @param movieStatus the value for yesapi_track_movie.movie_status
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setMovieStatus(Integer movieStatus) {
        this.movieStatus = movieStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.is_recommend
     *
     * @return the value of yesapi_track_movie.is_recommend
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Integer getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.is_recommend
     *
     * @param isRecommend the value for yesapi_track_movie.is_recommend
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setIsRecommend(Integer isRecommend) {
        this.isRecommend = isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.count
     *
     * @return the value of yesapi_track_movie.count
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.count
     *
     * @param count the value for yesapi_track_movie.count
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.create_time
     *
     * @return the value of yesapi_track_movie.create_time
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.create_time
     *
     * @param createTime the value for yesapi_track_movie.create_time
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.valid
     *
     * @return the value of yesapi_track_movie.valid
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.valid
     *
     * @param valid the value for yesapi_track_movie.valid
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}