package com.example.ez.po;

public class YesapiTrackMovieWithBLOBs extends YesapiTrackMovie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.track_movie_desc
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private String trackMovieDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yesapi_track_movie.music_desc
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    private String musicDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.track_movie_desc
     *
     * @return the value of yesapi_track_movie.track_movie_desc
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public String getTrackMovieDesc() {
        return trackMovieDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.track_movie_desc
     *
     * @param trackMovieDesc the value for yesapi_track_movie.track_movie_desc
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setTrackMovieDesc(String trackMovieDesc) {
        this.trackMovieDesc = trackMovieDesc == null ? null : trackMovieDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yesapi_track_movie.music_desc
     *
     * @return the value of yesapi_track_movie.music_desc
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public String getMusicDesc() {
        return musicDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yesapi_track_movie.music_desc
     *
     * @param musicDesc the value for yesapi_track_movie.music_desc
     *
     * @mbggenerated Thu Apr 21 13:24:50 CST 2022
     */
    public void setMusicDesc(String musicDesc) {
        this.musicDesc = musicDesc == null ? null : musicDesc.trim();
    }
}